version: '3.8'

services:
  restaurant-website:
    container_name: restaurant-website
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - website-data:/var/www/html/public

  nginx:
    image: nginx:stable-alpine
    ports:
      - ${LOCAL_PORT}:${NGINX_PORT}
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - LOCAL_PORT=${LOCAL_PORT}
    volumes:
      - website-data:/var/www/html/public
      - ./.docker/nginx/grilli.com.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - restaurant-website

volumes:
  website-data: