version: '3.8'

services:
  restaurant-website:
    container_name: restaurant-website
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - website-data:/var/www/html/public
    env_file:
      - .env.prod

  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - website-data:/var/www/html/public
      - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - restaurant-website

volumes:
  website-data:

# BIND PORTS WITH ENV VARIABLES