version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-server
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

  client:
    build: ./client
    container_name: client

  server:
    build: ./server
    container_name: server
