version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:${NGINX_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - NGINX_PORT=${NGINX_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - client
      - server

  client:
    build: ./client

  server:
    build: ./server
