version: '3.8'

services:
  nginx-server-tv-shows:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

  client-tv-shows:
    build: ./client

  server-tv-shows:
    build: ./server
